<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Dapper" />
	  <PackageReference Include="Microsoft.Data.SqlClient" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\..\BuildingBlocks\CrateSync.Platform.BuildingBlocks.Infrastructure\CrateSync.Platform.BuildingBlocks.Infrastructure.csproj" />
	  <ProjectReference Include="..\CrateSync.Platform.Catalog.Application\CrateSync.Platform.Catalog.Application.csproj" />
	  <ProjectReference Include="..\CrateSync.Platform.Catalog.Domain\CrateSync.Platform.Catalog.Domain.csproj" />
	</ItemGroup>
</Project>
